feat: use PDM
Snipy7374/dispatcher pull request #7
Opened 2023-03-09 07:42 UTC by ItsAleph

This PR sets up the repo to use [PDM](https://pdm.fming.dev/), similarly to disnake.

2023-03-09 09:53 UTC, Snipy7374 requested changes

2023-03-09 09:53 UTC, Snipy7374 commented on .gitignore
> +.pdm.toml
We need to ignore `pdm.lock` too

2023-03-09 11:02 UTC, ItsAleph commented on .gitignore
> +.pdm.toml
No, we do not. pdm.lock is necessary to keep dependencies at their exact versions, just like poetry's lock files. See [docs](https://pdm.fming.dev/latest/usage/project/#working-with-version-control) on that.

2023-03-09 13:47 UTC, ItsAleph commented on .gitignore
> +.pdm.toml
It was decided to gitignore pdm.lock *for now*.

2023-03-10 06:31 UTC, Snipy7374 approved these changes
Thanks!

2023-03-10 06:31 UTC, merged